title: ColliFlow
email: mateen_ulhaq@sfu.ca
description: >-
  A Library for Executing Collaborative Intelligence Graphs
github_username:  yodaembedding

markdown: kramdown
# theme: minima
theme: jekyll-theme-cayman
plugins:
  - jekyll-feed

github:
  is_project_page: false

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
